- .github/workflows/generate-doc.yaml
- .github/workflows/main.yaml
- apps/developer-docs/docs/guide/index.md
> Update docs and publish workflow

- .github/workflows/generate-doc.yaml
- apps/developer-docs/docs/guide/commit-format.md
#13 
Another docs publish test
> Update docs and publish workflow again

- .github/workflows/generate-doc.yaml
- apps/developer-docs/docs/guide/contributing.md
- apps/developer-docs/docs/guide/technology.md
> Docs typo and publish workflow again #13

- .github/workflows/generate-doc.yaml
- apps/developer-docs/docs/guide/technology.md
Deploy for the 6th time! This should fix the permissions issue
> Docs deploy access token

- .github/workflows/generate-doc.yaml
- .github/workflows/main.yaml
- .github/workflows/pr-commit.yaml
Close #44 
There may be some issues converting to PNPM and using the cache. This is is mostly running `affected` through Nx, the Python app may not benefit yet. I will keep an eye on it.
> Add lint, format, build, test CI jobs

- subset.config.js
- tools/scripts/package-subset.js
> Add package subset script #25

- apps/api-evidence/src/pre_start.py
> :bug: [api]: fix file encryption key encoding #99

- apps/api-dispute/poetry.lock
- apps/api-dispute/pyproject.toml
- apps/api-dispute/src/app/api/events.py
- apps/api-dispute/src/app/db/init_db.py
- apps/api-dispute/src/app/schemas/event.py
- apps/api-dispute/src/app/tests/test_api.py
> Add dispute completed webhook #87

- apps/api-evidence/src/app/utils/security.py
> fix typo in api-evidence

- package.json
> Update nx-python-fastapi #153

- .github/actions/setup-python-app/action.yml
- .github/workflows/pr-commit.yaml
- .prettierignore
- apps/api-dispute/pyproject.toml
- apps/api-dispute/src/app/tests/test_api.py
- apps/api-evidence/project.json
- apps/api-evidence/pyproject.toml
> add format check for python apps

- .husky/pre-commit
- .husky/pre-push
> Move some script from pre-commit to pre-push

- json-schema-to-typescript.d.ts
- libs/blockchain-watcher/feature-app/src/lib/service/ethService.ts
> Watcher error handling

- apps/api-dispute/poetry.lock
- apps/api-dispute/pyproject.toml
- apps/api-dispute/src/app/tests/test_api.py
- apps/api-dispute/src/app/utils/typing.py
> Fix address validation for checksum address

- skaffold.yaml
Close #201 
Luckily this was fixed with a simple helm chart update.
> Update nginx ingress controller #201

- apps/contracts/src/contracts/SlmChargeback.sol
- apps/contracts/src/contracts/SlmEscrow.sol
- apps/contracts/src/contracts/SlmFactory.sol
- apps/contracts/src/contracts/SlmPreorder.sol
- apps/contracts/src/contracts/SlmStakerManager.sol
- apps/contracts/src/contracts/SlmStakerStorage.sol
- apps/contracts/src/contracts/library/SlmJudgement.sol
- apps/contracts/src/contracts/library/SlmShared.sol
- apps/contracts/src/tests/SlmChargebacks.ts
- apps/contracts/src/tests/SlmJurors.ts
- apps/contracts/src/tests/SlmPreorder.ts
- apps/contracts/src/tests/SlmStakerManager.ts
- apps/contracts/src/tests/SlmStakerStorage.ts
Close #192, #68, #191
@jtse0 I cherry-picked the new commits from #194 after merging #188. The conflicts were a bit messy, so you'll probably want to take a look at this before we merge.
It's difficult for me to follow some of the tests, but I think we can take a look at things on a case by case basis after merging.
> Contract enhancements

- apps/contracts/src/contracts/SlmFactory.sol
- apps/contracts/src/scripts/deploy.ts
- apps/contracts/src/scripts/deployUtils.ts
- apps/contracts/src/tests/SlmJurors.ts
- apps/contracts/src/tests/testing.ts
> 196 contract deploy script

- apps/contracts/src/contracts/SlmChargeback.sol
- apps/contracts/src/contracts/SlmEscrow.sol
- apps/contracts/src/contracts/SlmFactory.sol
- apps/contracts/src/contracts/SlmPreorder.sol
- apps/contracts/src/contracts/SlmStakerManager.sol
- apps/contracts/src/contracts/library/SlmJudgement.sol
- apps/contracts/src/contracts/library/SlmShared.sol
- apps/contracts/src/scripts/deploy.ts
- apps/contracts/src/scripts/deployUtils.ts
- apps/contracts/src/tests/SlmChargebacks.ts
- apps/contracts/src/tests/SlmEscrow.ts
- apps/contracts/src/tests/SlmJurors.ts
- apps/contracts/src/tests/SlmPreorder.ts
- apps/contracts/src/tests/SlmStakerManager.ts
- apps/contracts/src/tests/SlmStakerStorage.ts
- apps/contracts/src/tests/testing.ts
> 207 contract merges

- apps/web-evidence/.eslintrc.js
- apps/web-evidence/index.html
- apps/web-evidence/src/app/App.vue
- apps/web-evidence/src/app/components/widgets/SlmHeader.vue
- apps/web-evidence/src/app/router.ts
- apps/web-evidence/src/app/translations/en.json
- apps/web-evidence/src/app/views/ContractSubmit.vue
- apps/web-evidence/src/app/views/ExternalLink.vue
- apps/web-evidence/src/app/views/Home.vue
- apps/web-evidence/src/app/views/SelectMethod.vue
- apps/web-evidence/src/app/views/SolomonLink.vue
- libs/web/plugin/src/lib/SlmPlugin.vue
- libs/web/ui-widgets/src/lib/ErrorMessage.vue
- libs/web/ui-widgets/src/lib/form/FileUpload.vue
- package.json
- subset.config.js
- tsconfig.base.json
Close #5 
Closing the issue since it will be blocked on API migration. A new issue will be created to track evidence submission.
> Include vue3-eth and add metamask to web-evidence #5

- apps/api/src/app.module.ts
- apps/api/src/auth/admin.guard.ts
- apps/api/src/auth/auth.controller.spec.ts
- apps/api/src/auth/auth.controller.ts
- apps/api/src/auth/auth.guard.ts
- apps/api/src/auth/auth.module.ts
- apps/api/src/auth/auth.service.spec.ts
- apps/api/src/auth/auth.service.ts
- apps/api/src/evidence/evidence.controller.ts
- apps/api/src/main.ts
- apps/api/src/user/user.controller.ts
- apps/app-e2e/src/api-auth.spec.ts
- apps/app-e2e/src/api-user.spec.ts
- libs/backend/service-db/src/lib/service/dbService.ts
- libs/backend/service-db/src/lib/service/evidenceDbService.spec.ts
- libs/backend/service-db/src/lib/service/evidenceDbService.ts
- libs/backend/service-db/src/lib/service/userDbService.spec.ts
- libs/backend/service-db/src/lib/service/userDbService.ts
- libs/shared/store-env/src/lib/envStore.ts
- libs/shared/util-klass/src/lib/EvidenceResult.ts
- libs/shared/util-klass/src/lib/UserResult.ts
- package.json
- tools/scripts/generateDBSchema.ts
- tools/scripts/insertRootAdmin.ts
- tools/tsconfig.json
> User api e2e & Auth
